//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eUniversity.Common.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eUniversity.Common.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвержденный.
        /// </summary>
        public static string Common_Approved {
            get {
                return ResourceManager.GetString("Common_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться к авторизации.
        /// </summary>
        public static string Common_BackToLogin {
            get {
                return ResourceManager.GetString("Common_BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляем!.
        /// </summary>
        public static string Common_Congrats {
            get {
                return ResourceManager.GetString("Common_Congrats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создан.
        /// </summary>
        public static string Common_Create {
            get {
                return ResourceManager.GetString("Common_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Common_Description {
            get {
                return ResourceManager.GetString("Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не Подтвержденный.
        /// </summary>
        public static string Common_Draft {
            get {
                return ResourceManager.GetString("Common_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последнее обновление.
        /// </summary>
        public static string Common_LastUpdated {
            get {
                return ResourceManager.GetString("Common_LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Common_Login {
            get {
                return ResourceManager.GetString("Common_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string Common_LogOut {
            get {
                return ResourceManager.GetString("Common_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Common_Name {
            get {
                return ResourceManager.GetString("Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Common_Password {
            get {
                return ResourceManager.GetString("Common_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        public static string Common_Profile {
            get {
                return ResourceManager.GetString("Common_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Common_Register {
            get {
                return ResourceManager.GetString("Common_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите пароль.
        /// </summary>
        public static string Common_RepeatPassword {
            get {
                return ResourceManager.GetString("Common_RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить.
        /// </summary>
        public static string Common_Reset {
            get {
                return ResourceManager.GetString("Common_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить!.
        /// </summary>
        public static string Common_SendMe {
            get {
                return ResourceManager.GetString("Common_SendMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string Common_Status {
            get {
                return ResourceManager.GetString("Common_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Common_Title {
            get {
                return ResourceManager.GetString("Common_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последнее обновление.
        /// </summary>
        public static string Common_Update {
            get {
                return ResourceManager.GetString("Common_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет.
        /// </summary>
        public static string Common_Welcome {
            get {
                return ResourceManager.GetString("Common_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль для отправки инструкций.
        /// </summary>
        public static string ForgotPassword_Details {
            get {
                return ResourceManager.GetString("ForgotPassword_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Востановление пароля.
        /// </summary>
        public static string ForgotPassword_Title {
            get {
                return ResourceManager.GetString("ForgotPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите логин и пароль.
        /// </summary>
        public static string Login_EnterLogin {
            get {
                return ResourceManager.GetString("Login_EnterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я забыл пароль.
        /// </summary>
        public static string Login_IForgotPassword {
            get {
                return ResourceManager.GetString("Login_IForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string Login_IWantToRegister {
            get {
                return ResourceManager.GetString("Login_IWantToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Login_Login {
            get {
                return ResourceManager.GetString("Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня?.
        /// </summary>
        public static string Login_RememberMe {
            get {
                return ResourceManager.GetString("Login_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить Регистрацию.
        /// </summary>
        public static string Membersip_ApproveAccount {
            get {
                return ResourceManager.GetString("Membersip_ApproveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить Пользователя.
        /// </summary>
        public static string Membersip_DeleteAccount {
            get {
                return ResourceManager.GetString("Membersip_DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посмотреть Профиль.
        /// </summary>
        public static string Membersip_ShowProfile {
            get {
                return ResourceManager.GetString("Membersip_ShowProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите ваши данные, чтобы начать:.
        /// </summary>
        public static string Register_EnterYourDetailsToBegin {
            get {
                return ResourceManager.GetString("Register_EnterYourDetailsToBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация пользователя.
        /// </summary>
        public static string Register_NewUser {
            get {
                return ResourceManager.GetString("Register_NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы зарегистрированны! Ожидайте подтверждения..
        /// </summary>
        public static string Register_SuccessufullyRegistration {
            get {
                return ResourceManager.GetString("Register_SuccessufullyRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип предмета.
        /// </summary>
        public static string Subject_Type {
            get {
                return ResourceManager.GetString("Subject_Type", resourceCulture);
            }
        }
    }
}
